### ISSUE TITLE
Site fixes

### ISSUE THREAD

**Issue by devdrops** [zendframework/zf3-web#11]
Found at https://docs.zendframework.com:

* Scroll down to the bottom in some pages hides part of the navigation menu:
    * Before:
    <img width="1276" alt="captura de tela 2016-06-28 as 17 50 36" src="https://cloud.githubusercontent.com/assets/1259313/16431871/eec4af4c-3d58-11e6-8c28-fc240e4100f7.png">

    * After:
    <img width="1277" alt="captura de tela 2016-06-28 as 17 50 45" src="https://cloud.githubusercontent.com/assets/1259313/16431874/f1a1300a-3d58-11e6-8990-74d052ff0574.png">

* `Home` always point to the same page instead of index, as well as the breadcrumb `DOCS` step (there is no link to the Docs index page, except at the footer):
    * Detail:    
    <img width="487" alt="captura de tela 2016-06-28 as 17 52 19" src="https://cloud.githubusercontent.com/assets/1259313/16431931/2fc60efa-3d59-11e6-9012-2e3d5d98410b.png">

**Comment by froschdesign** [comment]
@devdrops 
Problems in the theme of the docs should reported here: https://github.com/zendframework/zf-mkdoc-theme/issues

**Comment by devdrops** [comment]
@froschdesign my bad, I'm moving the issue to the right repository, thanks!
