### ISSUE TITLE
Redirect for old manual URL is missing

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf3-web#15]
See: https://framework.zend.com/manual

**Comment by ezimuel** [comment]
@froschdesign the URL /manual is still supported using the full path, for instance:
https://framework.zend.com/manual/2.4/en/index.html

**Comment by froschdesign** [comment]
@ezimuel 
Right, but "/manual" creates a 404 error. Maybe a simple redirect in ".htaccess"?

**Comment by ezimuel** [comment]
@froschdesign the question is "/manual" should resolve what? Even the previous website /manual was 404.

**Comment by froschdesign** [comment]
> Even the previous website /manual was 404.

Really?! Ugly URL design.
Okay, then we can ignore this.
