### ISSUE TITLE
TOC for ZF 1.10 and 1.9 are not working

### ISSUE THREAD

**Issue by ezimuel** [zendframework/zf3-web#22]
The Table Of Contents for ZF 1.10 and 1.9 are not working, empty page:
- https://framework.zend.com/manual/1.10/en/introduction.html
- https://framework.zend.com/manual/1.9/en/introduction.html

**Comment by froschdesign** [comment]
@ezimuel 
We had the same problem in old version: https://github.com/zendframework/zf-web/issues/129

**Comment by ezimuel** [comment]
@froschdesign I fixed the TOC for 1.9. I'm working now on 1.10.

**Comment by ezimuel** [comment]
@froschdesign Fixed also TOC of 1.10.
