### ISSUE TITLE
Many duplicate files in data/posts

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf3-web#23]
### Example 1

- [welcome.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/welcome.md)
- [2011-08-08-Welcome.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/2011-08-08-Welcome.md)

### Example 2

- [2011-08-19-Dev_status.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/2011-08-19-Dev_status.md)
- [2011-08-19-dev-status-update.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/2011-08-19-dev-status-update.md)

### Example 3

- [2011-08-17-IRC_Meeting_Log.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/2011-08-17-IRC_Meeting_Log.md)
- [2011-08-17-irc-meeting-log.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/2011-08-17-irc-meeting-log.md)

Which ends in duplicate blog posts! ([Example 1](https://framework.zend.com/blog?page=21), [Example 2](https://framework.zend.com/blog?page=20), [Example 3](https://framework.zend.com/blog?page=20))

Ping @weierophinney and @ezimuel

**Comment by ezimuel** [comment]
@froschdesign thanks for reporting this. I'll fix asap.
