### ISSUE TITLE
Double listed blog posts

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf3-web#30]
- "Zend Framework 3 Update and Roadmap": https://framework.zend.com/blog?page=4
- "Announcing the Zend Framework 3 Roadmap": https://framework.zend.com/blog?page=6

But there is only one file for each post!

ping @ezimuel

**Comment by froschdesign** [comment]
The same permalinks is the problem:

- /blog/zend-framework-3-update-and-roadmap.html
  - [2015-11-25-ZF3-Update.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/2015-11-25-ZF3-Update.md)
  - [zend-framework-3-update-and-roadmap.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/zend-framework-3-update-and-roadmap.md)
- /blog/announcing-the-zend-framework-3-roadmap.html
  - [announcing-the-zend-framework-3-roadmap.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/announcing-the-zend-framework-3-roadmap.md)
  - [2015-01-22-ZF3-Roadmap.md](https://github.com/zendframework/zf3-web/blob/master/data/posts/2015-01-22-ZF3-Roadmap.md)

**Comment by weierophinney** [comment]
I think I found and eliminated all of these and a few others.

Thanks!
