### ISSUE TITLE
Version numbers in Api configuration are outdated

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf3-web#31]
https://github.com/zendframework/zf3-web/blob/master/config/autoload/api.global.php

Related to [zf1/#731](/zendframework/zf1/issues/731)

**Comment by froschdesign** [comment]
ping @ezimuel

**Comment by GitRon** [comment]
Hm, seems that the persons in charge are not available right now...

**Comment by GitRon** [comment]
@weierophinney updated the versions on 20th Dec, maybe he'll do it again?

**Comment by GitRon** [comment]
@ezimuel Thanks 👍
