### ISSUE TITLE
ZF Blog Print (CSS) Firefox and IE

### ISSUE THREAD

**Issue by mike-a** [zendframework/zf3-web#86]
I tend to print and read but for the Blog that's not possible except in Chrome. For example, try printing https://framework.zend.com/blog/2017-04-26-authentication-middleware.html in Firefox or IE. I first saw this issue on Windows PC with latest Firefox around June 2017. Looks like the site as a whole has responsive design issues.

Separately, for a major framework series producer, this site "bug" (if it is one and not my systems) indicates a failure in site testing, attention to detail and community traction for they did not report. These type of issues repel developers that then go to frameworks that use ZF modules. Take a look at the second link under heading "Conclusion": what would developers think of that type of mistake? That second link does not address the URI indicated.

**Comment by ezimuel** [comment]
@mike-a We need to fix the CSS for printing, you right. @webimpress just fixed the link in the article that you mentioned with PR #87. Remember that Zend Framework is a community effort project, that means we accept collaborations from anyone. If you see something that is broken and you can fix it, please send a PR. Thanks!

**Comment by webimpress** [comment]
@ezimuel @mike-a I'm working on fix the CSS for printing right now

**Comment by ezimuel** [comment]
@webimpress Thanks!

**Comment by mike-a** [comment]
@ezimuel Fast response and fixes -- nice!

As for the comment about ZF being a community project, I shall have to disagree in part. Upon a fastidious investigation of the whole business model over a long period of time, it is a business model whereby a company (Zend/Rogue Wave) encourages a developer community to contribute, test, observe problems and provide fixes before taking intellectual rights over that community work. Upon that IR they derive an income stream from training, certification, products like server and studio, and customer contracts. Although the business model passes back framework components to the community, it charges for products and services that without community input would probably not exist, and saves a massive amount of expenditure on R & D otherwise necessary to gain an income stream.

From me: terse, but as a ZF/Expressive fan since 2008, designed to encourage a change of mindset by those at the top. Too many developers were unnecessarily lost to other frameworks. I see and congratulate major improvements in approach made by the ZF team this year but I don't want to see the "community effort" card played. Developers at architectural and framework development level are not dumb. My flagging an obvious, and avoidable, failure was not an open door to encourage me to provide free "consultative services"!  ;)

**Comment by ezimuel** [comment]
@mike-a the business model that you describe is the open source business. Zend/Rogue Wave is sponsoring the project, that means putting a bugdet for R&D, support, marketing, sponsoring events, etc. Me and @weierophinney work full time on the project, doing mostly R&D and support. We provide the initial effort for the start up of new components, like [Expressive](https://docs.zendframework.com/zend-expressive/), and the community give us a big help in growing and improving the source code. 

We are not asking to provide free "consultancy services" to our contributors. If you use the project during your daily job and you find a problem, you can open an issue on github and we will do our best to fix it. If you know the solution, you are more than welcome to send a PR to fix it. You can build (commercial) softwares using Zend Framework for free. If you want, you can help us to improve the software. We are sharing knowledge, that's it.

Zend Framework is an open source project, like any other PHP framework. The company that sponsor the project does not decide the new components to build, the community does. We accept contributions from anyone and we share our effort for free. The company that sponsor the project needs to have a return of investment, of course. For instance, providing consultancies or selling commercial softwares. I don't see any ethical problem with this business. IMHO this is the only way to have a long life open source projects, you need a company/organization/association that sponsor a project.
